### ISSUE TITLE
tap result description bug

### ISSUE THREAD

**Issue by Gabib32** [clearlinux/diva#124]
Tap results are reporting the same description for "ok" and "not ok", so for example:
"not ok 47 - file hashes for python2-basic bundle match hashes in manifest"
should be: "not ok 47 - file hashes for python2-basic bundle DO NOT match hashes in manifest"

**Comment by matthewrsj** [comment]
No, it should always report the check description. The `not ok` vs `ok` indicates if that check that is described passed or not.
