### ISSUE TITLE
Support for rpm file permissions

### ISSUE THREAD

**Issue by phmccarty** [clearlinux/diva#23]
Since the go-rpm FileInfo struct implements os.FileInfo from the standard library, the Permissions field in the DIVA File struct can likely use https://golang.org/pkg/os/#FileMode.Perm to store the permission bits as a string.

Example here: https://godoc.org/github.com/cavaliercoder/go-rpm#PackageFile.Files

**Comment by matthewrsj** [comment]
Fixed by #27
