### ISSUE TITLE
Support for rpm file hashes and symlink targets

### ISSUE THREAD

**Issue by phmccarty** [clearlinux/diva#24]
I don't see rpm file hashes (md5sums) or symlink targets tracked by go-rpm. Right now, its FileInfo struct implements only os.FileInfo, but it can be extended to support additional fields.

In rpm headers, md5sums are stored in the `FILEDIGESTS` field, and it's the empty string for directories. Symlink targets are stored in the `FILELINKTOS` field, and it's the empty string for non-symlinks.

In go-rpm, it looks like field values are extracted by offsets into the rpm header. [See this function](https://github.com/cavaliercoder/go-rpm/blob/972514cbf4/packagefile.go#L323).

**Comment by matthewrsj** [comment]
https://github.com/cavaliercoder/go-rpm/pull/14 opened against upstream to solve this issue.

**Comment by phmccarty** [comment]
Already merged :-)

**Comment by matthewrsj** [comment]
Fixed by #27
